services:
  - type: web
    name: stayfinder-frontend
    env: static
    buildCommand: cd src && npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false 